name: app_launcher_icon_widget
description: "Flutter plugin providing a widget and data for displaying the app launcher icon."
version: 0.0.1
homepage: https://github.com/sharmadhiraj/app-launcher-icon-widget

environment:
  sdk: '>=3.2.1 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2


flutter:
  plugin:
    platforms:
      android:
        package: com.sharmadhiraj.app_launcher_icon_widget
        pluginClass: AppLauncherIconWidgetPlugin
      ios:
        pluginClass: AppLauncherIconWidgetPlugin